name = "caveful_games/rbx_api_dump"
version = "0.1.0"
description = "A simple and reasonable module for working with the API dump from inside Roblox using Lune"
license = "MIT"
authors = ["Micah Reid <dekkonot@rocketmail.com>", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/CavefulGames/rbx-api-dump-lune"
private = false
includes = ["README.md", "LICENSE", "src/**", "pesde.toml"]

[target]
environment = "lune"
lib = "src/lib.luau"

[engines]
pesde = "^0.7.0-rc.1"
lune = "^0.9.4"

[dependencies.signal]
name = "jiwonz/signal"
version = "^0.1.0"
index = "https://github.com/pesde-pkg/index"
