name = "hugodzibetti/brickpack"
version = "0.1.0"
description = "A ultra fast and size effective instance serialization library."
authors = ["hugodzibetti"]
license = "MIT"

[target]
environment = "roblox"

[engines]
lune = "^0.8.0"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
install-packages = "scripts/InstallPackages.luau"
convert-requires = "scripts/ConvertRequires/init.luau"

[dependencies]