[package]
name = "hugod/rbx-instance-serializer"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
dump-parser = "csqrl/dump-parser@0.1.2"
testez = "roblox/testez@0.4.1"
buffer-util = "sleitnick/buffer-util@0.3.2"