name = "jiwonz/task"
version = "0.2.0-rc.2"
description = "Get the task library for Roblox or Lune or Luau"
license = "MIT"
authors = ["jiwonz <me@jiwonz.kr>", "jackdotink"]
repository = "https://github.com/jiwonz/luau-task"
private = false
includes = ["src/**", "pesde.toml", "LICENSE", "README.md"]

[target]
environment = "lune"
lib = "src/lib/init.luau"

[engines]
pesde = "^0.6.0"
lune = "^0.8.9"
