name = "jiwonz/go"
version = "0.2.0"
description = "Execute the functions in a separate thread, threads are pooled and reused. Credit to lukadev-0/util.luau"
license = "MIT"
authors = ["LukaDev <luka@lukadev.me> (https://lukadev.me/)", "jiwonz <me@jiwonz.kr>"]
repository = "https://github.com/jiwonz/luau-go"
private = false
includes = ["pesde.toml", "README.md", "src/**", "LICENSE", ".luaurc"]

[target]
environment = "lune"
lib = "src/lib.luau"

[dependencies.task]
name = "jiwonz/task"
version = "^0.2.0-rc.1"
index = "https://github.com/pesde-pkg/index"
