name = "itsfrank/frktest"
version = "0.0.2"
description = "A basic test framework for Lune"
license = "MIT"
authors = ["Francis O'Brien <github.com/itsfrank>"]
repository = "https://github.com/itsfrank/frktest"
private = false
includes = [".luaurc", "LICENSE", "README.md", "pesde.toml", "src"]

[target]
environment = "lune"
lib = "src/_pesde_init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
