name = "jiwonz/signal"
version = "0.1.0"
description = "Fast and simple signal class for Luau, Lune, and Roblox"
license = "MIT"
authors = ["jiwonz <me@jiwonz.kr>", "Aspecky", "Sona"]
repository = "https://github.com/jiwonz/luau-signal"
private = false
includes = ["LICENSE", "README.md", "src/**", "pesde.toml", ".luaurc"]

[target]
environment = "lune"
lib = "src/lib.luau"

[engines]
pesde = "^0.6.0-rc.8"
lune = "^0.8.9"

[dependencies.go]
name = "jiwonz/go"
version = "^0.2.0"
index = "https://github.com/pesde-pkg/index"

[dependencies.table_helper]
name = "caveful_games/table_helper"
version = "^0.2.0-rc.1"
index = "https://github.com/pesde-pkg/index"
target = "luau"

[dependencies.task]
name = "jiwonz/task"
version = "^0.2.0-rc.1"
index = "https://github.com/pesde-pkg/index"
