name = "caveful_games/table_helper"
version = "0.2.0-rc.1"
description = "A collection of helpful table utility functions extending TableUtil from RbxUtil for luau"
license = "MIT"
authors = ["jiwonz <me@jiwonz.kr>", "Stephen Leitnick"]
repository = "https://github.com/CavefulGames/table-helper-luau"
private = false
includes = ["src/**", "LICENSE", "pesde.toml", "README.md"]

[target]
environment = "luau"
lib = "src/lib/init.luau"

[engines]
pesde = "^0.6.0-rc.8"
lune = "^0.8.9"
